
type Resolution2 {
    id2: String!
    name2: String!
    subResolution2: SubResolution2
}

type SubResolution2{
    id: String!
    name: String!
    sub2Resolution2:  SubResolution2
}

extend type Mutation {
    createResolution2: Resolution2
}