version: '3'

services: 
  postgres:
      image: postgres
      #build: ./postgres
      #volumes:
        #- .database/postgres/data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=demo_db

      ports:
        - 5432:5432
